### ISSUE TITLE
Error on update customer (fails during retrieve)

### ISSUE THREAD

**Issue by bateller** [stripe/stripe-php#173]
Reference this issue: https://github.com/stripe/stripe-php/issues/24

On the latest Stripe-PHP I get this error when trying to retrieve customer data.

                        $key_secret = "sk_test_XXXXXXXXX";
                        $stripeID = "cus_XXXXXXXX";
                        $stripeToken = "tok_XXXXXXX";
                        require_once '../stripe_terminal/stripe-php/init.php';
                        \Stripe\Stripe::setApiKey($key_secret);
                        $cu = \Stripe\Customer::retrieve($stripeID);
                        $cu->description = 'Client Stuff';
                        $cu->source = $stripeToken; // obtained with Stripe.js
                        $cu->save();

Errors I'm receiving:
<b>Fatal error</b>:  Uncaught exception 'Stripe\Error\InvalidRequest' with message 'Could not determine which URL to request: Stripe\Customer instance has invalid ID: ' in /home/customerDIR/domains/customer.com/public_html/users/admin/stripe_terminal/stripe-php/lib/ApiResource.php:75
Stack trace:
#0 /home/customerDIR/domains/customer.com/public_html/users/admin/stripe_terminal/stripe-php/lib/ApiResource.php(20): Stripe\ApiResource-&gt;instanceUrl()
#1 /home/customerDIR/domains/customer.com/public_html/users/admin/stripe_terminal/stripe-php/lib/ApiResource.php(118): Stripe\ApiResource-&gt;refresh()
#2 /home/customerDIR/domains/customer.com/public_html/users/admin/stripe_terminal/stripe-php/lib/Customer.php(15): Stripe\ApiResource::_retrieve(NULL, NULL)
#3 /home/customerDIR/domains/customer.com/public_html/users/admin/actions/recurring_payments_edit.php(45): Stripe\Customer::retrieve(NULL)
#4 {main}
  thrown in <b>/home/customerDIR/domains/customer.com/public_html/users/admin/stripe_terminal/stripe-php/lib/ApiResource.php</b> on line <b>75</b><br />

**Comment by bateller** [comment]
Stupid user error. As the output says, my input $stripeID was null. Disregard.
