### ISSUE TITLE
PHP class "IssuerFraudRecord" not found?

### ISSUE THREAD

**Issue by DoobleD** [stripe/stripe-php#845]
Hi folks,

I got a strange issue, I think it's more likely to be a bug on my setup rather than Stripe but I can't figure out what's wrong. 

I use Stripe checkout and when I proceed to the payment, I get a PHP class not found error for "IssuerFraudRecord", from stripe-php/lib/Util/Util.php.

It seems [IssuerFraudRecord has been removed a while ago](https://github.com/stripe/stripe-php/pull/696), no idea why it's looking for it.

Any idea why this might occur?

What's really surprising is that it was working fine in the morning, then it broke later in the day, and I have no idea why. I didn't touch anything related to Stripe on that day.

I'm using Symfony 4.4 and nginx. I installed stripe-php via Composer:

> composer require stripe/stripe-php

Here is the stack trace:

```
2020/01/30 12:42:04 [error] 6083#6083: *101749 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "IssuerFraudRecord" from namespace "Stripe".
Did you forget a "use" statement for another namespace? in /opt/front/vendor/stripe/stripe-php/lib/Util/Util.php:104
Stack trace:
#0 /opt/front/vendor/stripe/stripe-php/lib/ApiOperations/Create.php(24): Stripe\Util\Util::convertToStripeObject(Array, Object(Stripe\Util\RequestOptions))
#1 /opt/front/src/Controller/DonateController.php(107): Stripe\Customer::create(Array)
#2 /opt/front/src/Controller/DonateController.php(53): App\Controller\DonateController->processPaymentRequest(Object(Symfony\Component\HttpFoundation\Request))
```

```
cat vendor/stripe/stripe-php/VERSION
7.21.1
```

When I open /opt/front/vendor/stripe/stripe-php/lib/Util/Util.php and look at line 104, I see no class IssuerFraudRecord, and I cleared Symfony's cache.

**Comment by DoobleD** [comment]
Ooook it was just because I didn't restart the docker container running all that. Sorry for this!
